import Image from "next/image";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@/styles/globals.scss";
import styles from "@/styles/layouts/layout.module.scss";

import Background from "@/assets/lights.png";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={styles.container} lang="en">
      <body className={inter.className}>
        <Image 
          src={Background}
          alt="Background"
          className={styles.background}
        />
        {children}
      </body>
    </html>
  );
}
